name: CI and SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build-and-analyze:
    name: Build, Test, SonarCloud Analysis, and Codecov Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Run Tests with Coverage
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit junit.xml

      - name: Check Coverage Report
        run: |
          if [ ! -f coverage.xml ]; then
            echo "Coverage report not found!"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java Version
        run: java -version

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=saami783_LSDA
            -Dsonar.organization=lsda
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.php.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/vendor/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true